# Generated by Django 2.2.4 on 2019-08-28 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=100)),
                ('book_author', models.CharField(max_length=50)),
                ('book_edition', models.CharField(max_length=50)),
                ('book_genre', models.CharField(max_length=50)),
                ('book_issued', models.BooleanField(default=False)),
                ('book_issuer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
